- hosts: localhost
  connection: local
  gather_facts: True
  
  #  vars:
  #  password: ' '
  tasks:
  - name: Include all variable files
    include_vars:
      dir: 'vars' #change directory if needed
      extensions:
        - yml
  - vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      guest: jojjtestansible
      state: powered_off
      esxi:
        datacenter: "{{ datacenter }}"
        hostname: "{{ hostname }}"

