- hosts: localhost
  connection: local
  gather_facts: True
  
  vars:
    password: 'Integration12'
  tasks:
  - vsphere_guest:
      vcenter_hostname: ukrdvmgvc001.dbpoc.uk
      username: isibor@dbpoc.uk
      password: "{{ password }}"
      validate_certs: no
      guest: jojjtestansible
      state: powered_off
      esxi:
        datacenter: Reading-Dev
        hostname: ukrdsesxi001.dbpoc.uk

